###BEGINNING/COLLABORATING WITH NEW DOCKER/JEKYLL PROJECT###
#====================================#

## 0. Set Shell JEKYLL_VERSION
# export JEKYLL_VERSION=4.0

## 1. Creating a New Project with Docker
# sudo docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:$JEKYLL_VERSION jekyll new mynewproject

## 2. Serving the Blog
# sudo docker run --name mynewproject --volume="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:$JEKYLL_VERSION jekyll serve --watch --drafts

## 3. [optional] Building an Existing Site for PRODUCTION _site directory
# sudo docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:$JEKYLL_VERSION jekyll build --trace

## 4. Setup docker-compose commands for easy & quicker docker container management [docker-compose --help]
## Create and start containers in relative directory
# docker-compose up
## Stop and remove containers, networks, images, and volumes
# docker-compose down

## Start docker services
# docker-compose start
## Stop docker services
# docker-compose stop

#====================================#

## Executing commands in the docker container
# docker exec -ti myblog gem install "jekyll-theme-hydeout"

## Removing docker container
# docker rm -f myblog

## Serve docker-compose container in . OR Serve manually
## docker-compose up
# docker run --name myblog --volume="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:$JEKYLL_VERSION jekyll serve --watch --drafts

## Discover container ID
# docker container ls

## Executing a shell in the container
# docker exec -ti 2d5913b926fc /bin/sh

## Copy template from docker jekyll site container shell
# cp -R /usr/local/bundle/gems/minima-2.5.1/ /srv/jekyll

# Change ownership from root to user:group after exit shell
## sudo chown -R username:group foldername/

#====================================#

version: '3'
services:
    jekyll-serve:
      image: jekyll/jekyll:4.0
      volumes:
        - '.:/srv/jekyll'
      ports:
        - 4000:4000
      command: 'jekyll serve --watch --drafts --verbose --trace'
